### ISSUE TITLE
404s do not raise X::NotFound

### ISSUE THREAD

**Issue by jakeonfire** [sferik/x-ruby#11]
it seems when the x API returns a resource not found error, `x-ruby` simply returns the JSON-parsed error response body as if the request were successful. e.g.

```ruby
client.get("users/by/username/doenotexist827")
{
  "errors" => [
    {
      "value"         => "doenotexist827",
      "detail"        => "Could not find user with username: [doenotexist827].",
      "title"         => "Not Found Error",
      "resource_type" => "user",
      "parameter"     => "username",
      "resource_id"   => "doenotexist827",
      "type"          => "https://api.twitter.com/2/problems/resource-not-found"
    }
  ]
}
```

**Comment by jakeonfire** [comment]
ah... seems this is an issue with X not returning the correct status code 😞 
```
<- "GET /2/users/by/username/doenotexist827 HTTP/1.1\r\nAccept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3\r\nAccept: */*\r\nHost: api.twitter.com\r\nContent-Type: application/json; charset=utf-8\r\nUser-Agent: X-Client/0.11.0 ruby/3.1.4 (aarch64-linux)\r\nAuthorization: OAuth oauth_consumer_key=\"[redacted]\", oauth_nonce=\"5897d928b2af85a623d38382f6050ff3\", oauth_signature=\"P%2F83t65bgYu5NFgq4I3io5J1w%2B0%3D\", oauth_signature_method=\"HMAC-SHA1\", oauth_timestamp=\"1698967170\", oauth_token=\"[redacted]\", oauth_version=\"1.0\"\r\nConnection: close\r\n\r\n"
-> "HTTP/1.1 200 OK\r\n"
-> "date: Thu, 02 Nov 2023 23:19:30 UTC\r\n"
-> "perf: 7626143928\r\n"
-> "server: tsa_p\r\n"
-> "set-cookie: guest_id_marketing=v1%3A169896717030328954; Max-Age=63072000; Expires=Sat, 01 Nov 2025 23:19:30 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None\r\n"
-> "set-cookie: guest_id_ads=v1%3A169896717030328954; Max-Age=63072000; Expires=Sat, 01 Nov 2025 23:19:30 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None\r\n"
-> "set-cookie: personalization_id=\"v1_OTPJHQ5lmfGf0f7NOMs+BA==\"; Max-Age=63072000; Expires=Sat, 01 Nov 2025 23:19:30 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None\r\n"
-> "set-cookie: guest_id=v1%3A169896717030328954; Max-Age=63072000; Expires=Sat, 01 Nov 2025 23:19:30 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None\r\n"
-> "api-version: 2.78\r\n"
-> "content-type: application/json; charset=utf-8\r\n"
-> "cache-control: no-cache, no-store, max-age=0\r\n"
-> "content-length: 195\r\n"
-> "x-access-level: read-write-directmessages\r\n"
-> "x-frame-options: SAMEORIGIN\r\n"
-> "content-encoding: gzip\r\n"
-> "x-transaction-id: 33c32b7ef25e8e1b\r\n"
-> "x-xss-protection: 0\r\n"
-> "x-rate-limit-limit: 900\r\n"
-> "x-rate-limit-reset: 1698967634\r\n"
-> "content-disposition: attachment; filename=json.json\r\n"
-> "x-content-type-options: nosniff\r\n"
-> "x-rate-limit-remaining: 895\r\n"
-> "strict-transport-security: max-age=631138519\r\n"
-> "x-response-time: 34\r\n"
-> "x-connection-hash: 473de5a578b1ee1a98ea5cb08954055fe522354259788295f2c511c275bf79ee\r\n"
-> "connection: close\r\n"
-> "\r\n"
reading 195 bytes...
-> "\x1F\x8B\b\x00\x00\x00\x00\x00\x00\x00l\x8E\xCB\n\xC20\x10E\x7F%dm\e\xE8F\xC9Vt\xE9\x0FH\x91\xD8Li \xED\x84d\xE2\x83\xD2\x7Fw\xE2\x03\x14\xDC\r\xF7q\xE6\xCE\x12b\xC4\x98\xA4>\xCE\xF2b|\x06\xA9\xA5E\x98\x90\xE0\xE6\x12m\x9A\xB5\\I\vd\x9Cgg\x8B\xD9[\xC1\xA6\xE8\xDDdEN\x10\xC5\xD5\xD1\xF0\xBC&3\x82\x16\xC7\xDFv[s\x9F\x1C\xF9\x02>pq\x8F\x99\x9B\xBB\xF2\x95\x9D\b\ts\xEC\xE0D\xF7P\x12\x85\xC3r0\x91a\xC4\xF7K*\xE8\xEF\xB4\xB3\xFFf\xBE\x19\x03QHZ)\x13\\M\xBC\x8E1u\x87\xA3jT\x88x\xF60&\xF5\x01U\f\xA8\xFA\xB2H.\xED\xF2\x00\x00\x00\xFF\xFF\x03\x00t\x1Ds\xD5\r\x01\x00\x00"
read 195 bytes
Conn close
```

**Comment by jakeonfire** [comment]
according to support:
> V2 implementation is different from V1.1. 

> In V2 response payload you will need to refer to the details and it wont return 404.

🤔

**Comment by jakeonfire** [comment]
<img width="366" alt="Screenshot 2023-11-06 at 1 53 45 PM" src="https://github.com/sferik/x-ruby/assets/68826/d67c5eaf-ed8d-46a5-bdab-63e28a128f55">
🤝

**Comment by sferik** [comment]
Hey @jakeonfire, thanks so much for your sponsorship! I’m looking into this issue now.

**Comment by sferik** [comment]
Thank you for brining this odd API behavior to my attention. In my opinion, this is quite a bad API design, but it’s what we have to work with.

Here are my initial thoughts about the best way to address this, but I’d love your feedback:

`X::NotFound` would be the parent class of `X::Error::NotFound` (HTTP status code 404) and `X::Problem::ResourceNotFound` (HTTP status code 200, as you describe above). This way you can `rescue X::NotFound` or a more specific error or problem if you prefer and existing code would not need to change (backward compatible). `X::NotFound` would continue to inherit from `X::HTTPError`, which itself inherits from `X::Error` (which inherits from `StandardError`). X gem users could `rescue` at any of these levels.

Similar `Twitter::Problem` classes would be defined for all of the [documented problems](https://developer.twitter.com/en/support/twitter-api/error-troubleshooting#error-information). 

What do you think of this approach?

**Comment by jakeonfire** [comment]
i think this is a good approach. i guess the hairy part is for multi-resource requests where some of the requested resources have a "problem" and some do not. do you think it works in this case as well?
fwiw this case doesn't concern our particular usage.

**Comment by jakeonfire** [comment]
here is the documentation on it: https://developer.twitter.com/en/support/twitter-api/error-troubleshooting (see second section: "Partial errors").

examples:
```ruby
client.get("tweets?ids=1721704226525466834,1821704226525466834")
{
  "data"   => [
    {
      "edit_history_tweet_ids" => [
        "1721704226525466834"
      ],
      "id"                     => "1721704226525466834",
      "text"                   => "24h je suis ici, w’Allah j’ai déjà vécu des moments de fou"
    }
  ],
  "errors" => [
    {
      "value"         => "1821704226525466834",
      "detail"        => "Could not find tweet with ids: [1821704226525466834].",
      "title"         => "Not Found Error",
      "resource_type" => "tweet",
      "parameter"     => "ids",
      "resource_id"   => "1821704226525466834",
      "type"          => "https://api.twitter.com/2/problems/resource-not-found"
    }
  ]
}
```

```ruby
client.get("users?ids=1299823560156942342,1399823560156942342")
{
  "data"   => [
    {
      "id"       => "1299823560156942342",
      "name"     => "🌼",
      "username" => "user48993"
    }
  ],
  "errors" => [
    {
      "value"         => "1399823560156942342",
      "detail"        => "Could not find user with ids: [1399823560156942342].",
      "title"         => "Not Found Error",
      "resource_type" => "user",
      "parameter"     => "ids",
      "resource_id"   => "1399823560156942342",
      "type"          => "https://api.twitter.com/2/problems/resource-not-found"
    }
  ]
}
```

**Comment by sferik** [comment]
@jakeonfire Thank you for providing those example responses. Given that they contain the requested data, in addition to errors, I don’t believe that raising an exception is appropriate. How would you expect this library handle these cases?

**Comment by jakeonfire** [comment]
i agree when there is successful response data _and_ an error that no error should be raised. i'm disappointed in X's decision to do something similar when either the _only_ requested resource returns just the error, and less so when all requested resources for multi-resource requests return errors:
```ruby
begin; client.get("users?ids=1399823560156942342,1399823560156942342"); rescue => e; puts e.response.body; end
{
  "errors" => [
    {
      "value"         => "1399823560156942342",
      "detail"        => "Could not find user with ids: [1399823560156942342].",
      "title"         => "Not Found Error",
      "resource_type" => "user",
      "parameter"     => "ids",
      "resource_id"   => "1399823560156942342",
      "type"          => "https://api.twitter.com/2/problems/resource-not-found"
    },
    {
      "value"         => "1399823560156942342",
      "detail"        => "Could not find user with ids: [1399823560156942342].",
      "title"         => "Not Found Error",
      "resource_type" => "user",
      "parameter"     => "ids",
      "resource_id"   => "1399823560156942342",
      "type"          => "https://api.twitter.com/2/problems/resource-not-found"
    }
  ]
}
```
if i were designing this API i would return 404 when a single resource is requested and not found. not sure what you think about handling just that case and raising `X::NotFound`? i leave it to your discretion, since it is quite the exceptional case (pun intended).

**Comment by jakeonfire** [comment]
maybe a less opinionated way to do it would be to allow some option to `#get` like `raise_on_not_found`? but then does it return `200` for `code`? ugh the perfectionist in me hates this.

**Comment by sferik** [comment]
I agree, the API designers’ decision to return 200 when a single resource is requested and not found is questionable. That said, I don’t want to get into the business of redesigning the API to my taste. This gem is intended to be a lightweight wrapper around the API, warts and all. If the API returns 200, raising an exception seems unwarranted, and would be unexpected to those familiar with the behavior of API v2.0.

Maybe instead of changing the code, we instead add some documentation, like a “Upgrading from API v1.1” guide or a “Gotchas” doc that highlights issues like this?

**Comment by jakeonfire** [comment]
up to you. i agree with your assessment. thanks for looking into this!
