### ISSUE TITLE
Get headers returned by Twitter

### ISSUE THREAD

**Issue by GCorbel** [sferik/x-ruby#16]
Response given by Twitter contains information about the rate limits and other data that may be useful.

> -> "HTTP/1.1 200 OK\r\n"
> -> "date: Thu, 23 Nov 2023 15:44:52 UTC\r\n"
> -> "perf: 7626143928\r\n"
> -> "server: tsa_b\r\n"
> -> "set-cookie: guest_id_marketing=v1%3A170075429285743641; Max-Age=63072000; Expires=Sat, 22 Nov 2025 15:44:52 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None\r\n"
> -> "set-cookie: guest_id_ads=v1%3A170075429285743641; Max-Age=63072000; Expires=Sat, 22 Nov 2025 15:44:52 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None\r\n"
> -> "set-cookie: personalization_id=\"v1_F8OwV3WQbDnvG1xa4FF69A==\"; Max-Age=63072000; Expires=Sat, 22 Nov 2025 15:44:52 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None\r\n"
> -> "set-cookie: guest_id=v1%3A170075429285743641; Max-Age=63072000; Expires=Sat, 22 Nov 2025 15:44:52 GMT; Path=/; Domain=.twitter.com;  Secure; SameSite=None\r\n"
> -> "api-version: 2.79\r\n"
> -> "content-type: application/json; charset=utf-8\r\n"
> -> "cache-control: no-cache, no-store, max-age=0\r\n"
> -> "content-length: 54\r\n"
> -> "x-access-level: read-write-directmessages\r\n"
> -> "x-frame-options: SAMEORIGIN\r\n"
> -> "content-encoding: gzip\r\n"
> -> **"x-transaction-id: ba2351ae9b0370b5\r\n"**
> -> "x-xss-protection: 0\r\n"
> -> **"x-rate-limit-limit: 50\r\n"**
> -> **"x-rate-limit-reset: 1700754708\r\n"**
> -> "content-disposition: attachment; filename=json.json\r\n"
> -> "x-content-type-options: nosniff\r\n"
> -> **"x-rate-limit-remaining: 44\r\n"**
> -> "strict-transport-security: max-age=631138519\r\n"
> -> "x-response-time: 57\r\n"
> -> "x-connection-hash: 00f7bb3d091cf40b4d08065a738aee106202e4164c397e2759a488d79fde1a60\r\n"
> -> "connection: close\r\n"

I want to use `x-rate-limit-reset` in order to block retries until this time.

ATM, the only way I see to have them it to override `X::Client#execute_request`. I don't like to prepend methods from external gems.

As said in https://github.com/sferik/x-ruby/issues/12, adding hooks is not very convenient. I have no better idea.

**Comment by GCorbel** [comment]
I didn't see that some headers are added in errors, since https://github.com/sferik/x-ruby/commit/b0036399672db699ac558fd1ff11530c04d777ae.

There is still no way to have them when there is no error, but it's correct to what I want to do.

**Comment by sferik** [comment]
As you noted, data from the rate limit headers is accessible when an `X::TooManyRequests` exception is raised. This should allow you to block retries until `x-rate-limit-reset`. Here is an [example](https://github.com/sferik/x-ruby/blob/main/examples/pagination.rb) of how to do that.

**Comment by GCorbel** [comment]
Ok but what if there is no error raised ? We may want to have headers when the request succeeds, for monitoring for example.

**Comment by sferik** [comment]
I’m curious to better understand your specific use case. If you’d like to track the number of requests you make, you can add instrumentation to each request, as I’ve suggested doing [here](https://github.com/sferik/x-ruby/issues/12).

I also noticed this is the [fourth issue you’ve opened on this project](https://github.com/sferik/x-ruby/issues?q=is%3Aissue+author%3Agcorbel). If you (or your company) would be willing to [sponsor me](https://github.com/sponsors/sferik), I would prioritize your issues and feature requests. (I would also list your name or your company’s logo on [this project’s GitHub page](https://sferik.github.io/x-ruby/#sponsors).)

**Comment by GCorbel** [comment]
> I’m curious to better understand your specific use case. 

The actual code is enough for what I have to do ATM. I suggested to expose headers as it can be useful in some use cases, as monitoring.

> If you’d like to track the number of requests you make, you can add instrumentation to each request, as I’ve suggested doing https://github.com/sferik/x-ruby/issues/12.

I don't really like to prepend/patch methods and I think this can be useful for some other users so I propose changes.

> I also noticed this is the [fourth issue you’ve opened on this project](https://github.com/sferik/x-ruby/issues?q=is%3Aissue+author%3Agcorbel). If you (or your company) would be willing to [sponsor me](https://github.com/sponsors/sferik), I would prioritize your issues and feature requests. I would also list your name or your company’s logo on [this project’s GitHub page](https://sferik.github.io/x-ruby/#sponsors).

I asked to my company and had no answer. I will ping them again. You did an awesome job and a important part of what I had to do but in better. This deserves a contribution.
