### ISSUE TITLE
Get monthly rate limits

### ISSUE THREAD

**Issue by tophertoy** [sferik/x-ruby#23]
Thanks for your work on this gem.

It's very useful!

Is there anyway to get monthly rate limits?

When we get a X::TooManyRequests I know we get rate limits from the response but these tend to be hourly. I need a way to track monthly rate limits and adjust API request attempts based on the monthly limits..

**Comment by sferik** [comment]
How does the API return monthly limits? Is it one of the header values of a 429 response? I wasn’t able to find any documentation on this.  If you can provide an example response, I can expand the [`X::RateLimit`](https://github.com/sferik/x-ruby/blob/main/lib/x/rate_limit.rb) object to parse and return the value.

**Comment by sferik** [comment]
@tophertoy It's been two weeks since I asked this question. I’m going to close this issue now but feel free to reopen it if you have a response.

**Comment by tophertoy** [comment]
Sorry for the delay. We had to stop using the gem for other reasons.

Apologies.

**Comment by tophertoy** [comment]
Twitter API costs.

**Comment by sferik** [comment]
Gotcha. Happy to hear it wasn’t an issue with this library specifically.
