### ISSUE TITLE
Add retweet support

### ISSUE THREAD

**Issue by kyrylo** [sferik/x-ruby#27]
https://developer.twitter.com/en/docs/twitter-api/tweets/retweets/quick-start/retweets-lookup

P.S. Apologies if this is already implemented (I did a quick search and couldn't find anything).

**Comment by sferik** [comment]
Retweets should be supported. Have you tried posting one? If so, what error are you getting?

**Comment by kyrylo** [comment]
Do you mind pointing me to the right file/example?

I am not familiar with how X/Twitter replies work.

**Comment by kyrylo** [comment]
This is how you're supposed to do it, apparently:

```rb
x_client = X::Client.new(**credentials)
x_client.post("users/YOUR_ID/retweets", '{"tweet_id": 1780748584775823851}')
```

If you're on the Free plan, you will see the following error:

> Client Forbidden: When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal. (X::Forbidden)

Retweets are supported starting with Basic.
